# Site information
site_name: Projeto MarGran
site_author: Cassio Menezes

# Copyright
copyright: Copyright &copy; 2024

# Configuration
theme:
  name: material
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    #- navigation.sections
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - tags:
      tags_file: tags.md
  - mermaid2

# Customization
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - toc:
      permalink: true
  - toc:
      permalink: "#"

# Page tree
nav:
  - Inicio: index.md
  - Visão Geral:
    - O que é o MarGran: 'overview/what-is-margran.md'
    - Arquitetura: 'overview/architectures-overview.md'
  - 'Estrutura de Dados': '_database/index.md'
  - Sobre: about.md
  - tags: 'tags.md'