# Site information
site_name: Projeto MarGran - Mármore e Granito Sankhya Om
site_author: Cassio Menezes

# Copyright
copyright: Copyright &copy; 2024

# Configuration
theme:
  name: material
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    #- navigation.sections
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono

# Page tree
nav:
  - Inicio: index.md
  - Sobre: about.md