# Site information
site_name: Projeto MarGran - Mármore e Granito Sankhya Om
site_author: Cassio Menezes

# Copyright
copyright: Copyright &copy; 2024

# Configuration
theme:
  name: material
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    #- navigation.sections
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - tags:
      tags_file: tags.md
  - mermaid2

# Page tree
nav:
  - Inicio: index.md
  - Visão Geral:
    - O que é o MarGran: 'overview/what-is-margran.md'
    - Arquitetura: 'overview/architectures-overview.md'
  - Sobre: about.md
  - tags: 'tags.md'